[package]
name = "dovi_tool"
version = "0.3.2"
authors = ["quietvoid"]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3.21"
indicatif = "0.16.2"
regex = "1.5.4"
ansi_term = "0.12.1"
crc = "2.0.0-rc.1"
bitvec = "0.20.1"
bitvec_helpers = "0.1.0"
hevc_parser = "0.1.3"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
